sudo: required
services:
- docker
language: bash
script:
- export REPO=whatever4711/picapport
- make amd64
- docker images
after_success:
- docker images
- make push
- make clean
- curl -X POST https://hooks.microbadger.com/images/whatever4711/picapport/h54qEvKKiyj8evp5FLbwRCouqks=
notifications:
  slack:
    secure: ${SLACK}
