version: 2
jobs:
  update:
    machine: true
    steps:
      - run: echo "Updating Docker engine to have multi-stage builds"
      - run: sudo service docker stop
      - run: curl -fsSL https://get.docker.com/ | sudo sh
      - run: docker version
  checkout:
    working_directory: ~/picapport
    machine: true
    steps:
      - checkout

workflows:
  version: 2
  update:
    jobs:
      - update
  checkout:
    jobs:
      - checkout
