version: 2
jobs:
  update:
    machine: true
    steps:
      - run: echo "Updating Docker engine to have multi-stage builds"
      - run: sudo service docker stop
      - run: curl -fsSL https://get.docker.com/ | sudo sh
      - run: docker version
  build_amd64:
    working_directory: ~/picapport
    machine: true
    steps:
      - checkout
      - run: export ARCHITECTURES=amd64
      - run: make
      - run: make push
  build_arm32v6:
    working_directory: ~/picapport
    machine: true
    steps:
      - checkout
      - run: export ARCHITECTURES=arm32v6
      - run: make
      - run: make push
  build_arm64v8:
    working_directory: ~/picapport
    machine: true
    steps:
      - checkout
      - run: export ARCHITECTURES=arm64v8
      - run: make
      - run: make push
  manifest:
    machine: true
    steps:
      - checkout


workflows:
  version: 2
  build-and-deploy:
    jobs:
      - update
      - build_amd64:
          requires:
            - update
      - build_arm32v6:
          requires:
            - update
      - build_arm64v8:
          requires:
            - update
      - manifest:
          requires:
            - build_amd64
            - build_arm32v6
            - build_arm64v8
